name: Deploy Backend Live

on:
  push:
    branches:
      - live
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Hostinger Live
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER_LIVE }}
          username: ${{ secrets.FTP_USERNAME_LIVE }}
          password: ${{ secrets.FTP_PASSWORD_LIVE }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /domains/demohandler.in/public_html/apisafarsystem/
          dangerous-clean-slate: false
          exclude: |
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/.env
            **/images/**
            **/public/images/**
            **/storage/*.key
            **/storage/app/**
            **/storage/framework/**
            **/storage/logs/**
            **/bootstrap/cache/**
            **/vendor/**
