name: Deploy Backend Stage

on:
  push:
    branches:
      - stage
      - develop

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Hostinger Stage
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.demohandler.in
          username: u479097380
          password: DemoHandler_1
          port: 21
          protocol: ftp
          security: loose
          local-dir: ./
          server-dir: /domains/demohandler.in/public_html/apisafarsystem/
          dangerous-clean-slate: false
          exclude: |
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/.env
            **/images/**
            **/public/images/**
            **/storage/*.key
            **/storage/framework/cache/data/*
            **/storage/framework/sessions/*
            **/storage/framework/views/*
            **/storage/logs/*.log
            **/bootstrap/cache/*.php
            **/vendor/**
