name: Deploy Backend Live

on:
  push:
    branches:
      - live
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Hostinger Live
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 145.79.211.128
          username: u479097380
          password: Demohandler_1
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /domains/demohandler.in/public_html/apisafarsystem/
          dangerous-clean-slate: false
          exclude: |
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/.env
            **/images/**
            **/public/images/**
            **/storage/*.key
            **/storage/app/**
            **/storage/framework/**
            **/storage/logs/**
            **/bootstrap/cache/**
            **/vendor/**
